version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: saffron_db_2
      MYSQL_USER: saffron_user
      MYSQL_PASSWORD: your_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bagisto_network
    ports:
      - "3306:3306"

  # phpMyAdmin - Database Management UI
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8090:80"
    networks:
      - bagisto_network
    depends_on:
      - db

networks:
  bagisto_network:
    driver: bridge

volumes:
  mysql_data: